--- 
- name: copy the files
  hosts: all
  become: yes
  var: 
    pradeep: devops
  tasks:
    - name: copy properties
      copy:
        src: /tmp/properties/
        dest: /opt/properties/
        owner: pradeep
        group: pradeep
        remote_src: yes
        backup: yes
        mode: 0775