--- 
- name: copy the files
  hosts: all
  become: yes
  tasks:
    - name: copy properties
      copy: 
        src: /tmp/properties
        dest: /opt/
        owner: devops
        group: devops
        mod: 0755