---
- name: install tomcat
  hosts: tomcat
  become: yes
  tasks: 
    - name: update ubuntu packages and install java
      apt: 
        name: openjdk-8-jdk
        update_cache: true
        state: present
    - name: install apachetomcat version 9
      get_url:
         url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.41/bin/apache-tomcat-9.0.41.tar.gz
         dest: /tmp
    - name: unzip the tar file
      unarchive:
         src: /tmp/apache-tomcat-9.0.41.tar.gz
         dest: /tmp/
         remote_src: yes
    - name: changing owner
      file:
        path: /tmp/apache-tomcat-9.0.41/bin
        owner: devops
        group: devops
        mode: '0755'
    - name: starting tomcat
      shell: /tmp/apache-tomcat-9.0.41/bin/startup.sh
        


    
      
            