---
- name: install tomcat
  hosts: tomcat
  become: yes
  tasks: 
    - name: update ubuntu packages and install java
      apt: 
        name: openjdk-8-jdk
        update_cache: true
        state: present
    - name: install apachetomcat version 9
      get_url:
         src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.41/bin/apache-tomcat-9.0.41.tar.gz
         dest: /tmp
    - name: unzip the tar file
      unarchive:
         src: /tmp/pache-tomcat-9.0.41.tar.gz
         dest: /tmp/
         remote_src: yes


    
      
            